### ISSUE TITLE
No static image received !

### ISSUE THREAD

**Issue by joubix** [iliasam/STM32F4_UVC_Camera#2]
Hello,
First thank you so much for posting this interesting project.
I just would like to know if the iar_uvc_mjpeg_static works correctly or not, because actually I tried to load that project on STM32f429I, however only the USB connection is established and no static image is received (I used Contacam). So, I would like to know if there is any possible adaptation to do on the code.
Thanks

**Comment by iliasam** [comment]
Hello.
I'm sorry - I found that it is really not working. It's look like that something go wrong when I publish project to Github. I will try to repair project code  in nearest future.

**Comment by iliasam** [comment]
I found the mistake and publish new commit.
Try it - it must work now.
